service: auth-server

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors: true
    layers:
      - { Ref: NodeModulesLambdaLayer }

  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/get-access-token/{code}
          method: get
          cors: true
    layers:
      - { Ref: NodeModulesLambdaLayer }

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors: true
    layers:
      - { Ref: NodeModulesLambdaLayer }

layers:
  nodeModules:
    path: lambda-layer
